# Generated by Django 2.0 on 2017-12-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=220)),
                ('lastName', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('email', models.CharField(blank=True, help_text='Ingrese Correo Electronico', max_length=120, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('mobileNumber', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
