# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-09 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobileNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
